apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-website
  namespace: intellipaat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intellipaat-website
  template:
    metadata:
      labels:
        app: intellipaat-website
    spec:
      containers:
        - name: intellipaat-website
          image: chiru0977/intellipaat-website:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
